-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.3
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Filter2D is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_src_rows_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    p_src_cols_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    p_src_data_stream_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    p_src_data_stream_V_empty_n : IN STD_LOGIC;
    p_src_data_stream_V_read : OUT STD_LOGIC;
    p_dst_data_stream_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_dst_data_stream_V_full_n : IN STD_LOGIC;
    p_dst_data_stream_V_write : OUT STD_LOGIC );
end;


architecture behav of Filter2D is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv32_FFFFFFFE : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111110";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv32_FFFFFFFD : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111101";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal p_src_data_stream_V_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal exitcond460_i_reg_1393 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond_i_i_reg_1402 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_reg_1358 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_reg_1349 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_dst_data_stream_V_blk_n : STD_LOGIC;
    signal or_cond_i_reg_1438 : STD_LOGIC_VECTOR (0 downto 0);
    signal t_V_2_reg_277 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_s_fu_288_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_s_reg_1306 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_fu_294_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_reg_1311 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_neg465_i_fu_300_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_neg465_i_reg_1316 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_fu_306_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_reg_1323 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_4_fu_318_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_4_reg_1328 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_8_fu_330_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_8_reg_1335 : STD_LOGIC_VECTOR (31 downto 0);
    signal exitcond461_i_fu_336_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal i_V_fu_341_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_V_reg_1344 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_5_fu_347_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_70_0_not_fu_352_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_70_0_not_reg_1353 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_fu_368_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_12_fu_374_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_12_reg_1363 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_114_1_fu_380_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_114_1_reg_1367 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_fu_386_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_reg_1371 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_23_fu_601_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_23_reg_1378 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_24_fu_626_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_24_reg_1383 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_32_fu_651_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_32_reg_1388 : STD_LOGIC_VECTOR (1 downto 0);
    signal exitcond460_i_fu_655_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state3_pp0_stage0_iter0 : BOOLEAN;
    signal ap_predicate_op154_read_state4 : BOOLEAN;
    signal ap_predicate_op165_read_state4 : BOOLEAN;
    signal ap_predicate_op218_write_state4 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal j_V_fu_660_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal or_cond_i_i_fu_707_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_fu_784_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_reg_1406 : STD_LOGIC_VECTOR (0 downto 0);
    signal k_buf_0_val_3_addr_reg_1413 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_37_fu_796_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_37_reg_1419 : STD_LOGIC_VECTOR (1 downto 0);
    signal k_buf_0_val_4_addr_reg_1426 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_buf_0_val_5_addr_reg_1432 : STD_LOGIC_VECTOR (10 downto 0);
    signal or_cond_i_fu_800_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal k_buf_0_val_3_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_buf_0_val_3_ce0 : STD_LOGIC;
    signal k_buf_0_val_3_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal k_buf_0_val_3_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_buf_0_val_3_ce1 : STD_LOGIC;
    signal k_buf_0_val_3_we1 : STD_LOGIC;
    signal k_buf_0_val_4_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_buf_0_val_4_ce0 : STD_LOGIC;
    signal k_buf_0_val_4_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal k_buf_0_val_4_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_buf_0_val_4_ce1 : STD_LOGIC;
    signal k_buf_0_val_4_we1 : STD_LOGIC;
    signal k_buf_0_val_4_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal k_buf_0_val_5_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_buf_0_val_5_ce0 : STD_LOGIC;
    signal k_buf_0_val_5_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal k_buf_0_val_5_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_buf_0_val_5_ce1 : STD_LOGIC;
    signal k_buf_0_val_5_we1 : STD_LOGIC;
    signal k_buf_0_val_5_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal t_V_reg_266 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal tmp_25_fu_789_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal src_kernel_win_0_va_fu_128 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_6_fu_924_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_1_fu_132 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_2_fu_136 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_7_fu_942_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_3_fu_140 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_4_fu_144 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_8_fu_960_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_5_fu_148 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_s_fu_152 : STD_LOGIC_VECTOR (7 downto 0);
    signal col_buf_0_val_0_0_fu_834_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_1_fu_156 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_2_fu_160 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_3_fu_164 : STD_LOGIC_VECTOR (7 downto 0);
    signal col_buf_0_val_1_0_fu_852_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_4_fu_168 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_5_fu_172 : STD_LOGIC_VECTOR (7 downto 0);
    signal col_buf_0_val_2_0_fu_870_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_3_fu_312_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_7_fu_324_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_10_fu_358_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_14_fu_391_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_15_fu_397_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_16_fu_411_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev_fu_405_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_17_fu_422_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_assign_7_fu_430_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_p2_i497_i_fu_436_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_assign_6_1_fu_454_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_19_fu_460_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_140_1_fu_474_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev1_fu_468_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_20_fu_485_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_assign_7_1_fu_493_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_p2_i497_i_1_fu_499_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_assign_6_2_fu_517_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_21_fu_523_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_140_2_fu_537_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev2_fu_531_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_22_fu_548_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_assign_7_2_fu_556_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_p2_i497_i_2_fu_562_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_18_fu_444_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_assign_8_fu_449_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_cond_i496_i_fu_416_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_p2_i497_i_p_assign_8_fu_580_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal y_fu_588_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal row_assign_9_fu_596_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_149_1_fu_507_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_assign_8_1_fu_512_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_cond_i496_i_1_fu_479_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_p2_i497_i_1_p_assig_fu_605_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal y_1_fu_613_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal row_assign_9_1_fu_621_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_149_2_fu_570_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_assign_8_2_fu_575_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_cond_i496_i_2_fu_542_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_p2_i497_i_2_p_assig_fu_630_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal y_2_fu_638_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal row_assign_9_2_fu_646_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_33_fu_666_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal ImagLoc_x_fu_682_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_34_fu_688_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_fu_702_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev3_fu_696_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_35_fu_713_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_assign_1_fu_721_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_p2_i_i_fu_727_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_assign_2_fu_740_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_9_not_fu_753_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_11_fu_735_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp7_fu_759_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp8_fu_765_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_assign_3_fu_745_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal x_fu_771_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal col_assign_1_fu_779_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp1_fu_676_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_26_fu_823_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_27_fu_841_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_28_fu_859_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_29_fu_913_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_30_fu_931_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_31_fu_949_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_156_0_2_cast_fu_980_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal r_V_0_cast_fu_976_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sum_V_0_2_fu_984_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_shl_fu_994_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_shl_cast_fu_1002_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal r_V_10_1_fu_1006_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal r_V_10_1_2_fu_1024_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal r_V_2_cast_fu_1042_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal r_V_10_2_fu_1046_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_156_2_cast_fu_1052_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_156_1_cast_fu_1012_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_156_2_2_cast_cas_fu_1060_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sum_V_0_2_cast_cast_fu_990_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp23_fu_1070_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_156_1_cast_63_fu_1032_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp23_cast_fu_1076_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp21_fu_1064_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp22_fu_1080_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_Val2_s_fu_1086_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_41_fu_1020_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_40_fu_1016_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_43_fu_1056_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_42_fu_1036_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp26_fu_1106_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp24_fu_1100_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp25_fu_1112_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_s_fu_1092_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_36_fu_1124_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal not_i_i_fu_1140_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_i_i_fu_1134_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal overflow_fu_1146_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_i_i_fu_1160_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_mux_i_i_cast_fu_1152_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Val2_1_fu_1118_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0 : BOOLEAN;
    signal ap_enable_operation_118 : BOOLEAN;
    signal ap_enable_state3_pp0_iter0_stage0 : BOOLEAN;
    signal ap_enable_operation_145 : BOOLEAN;
    signal ap_enable_state4_pp0_iter1_stage0 : BOOLEAN;
    signal ap_predicate_op159_store_state4 : BOOLEAN;
    signal ap_enable_operation_159 : BOOLEAN;
    signal ap_predicate_op166_store_state4 : BOOLEAN;
    signal ap_enable_operation_166 : BOOLEAN;
    signal ap_enable_operation_121 : BOOLEAN;
    signal ap_enable_operation_148 : BOOLEAN;
    signal ap_predicate_op157_store_state4 : BOOLEAN;
    signal ap_enable_operation_157 : BOOLEAN;
    signal ap_predicate_op164_store_state4 : BOOLEAN;
    signal ap_enable_operation_164 : BOOLEAN;
    signal ap_enable_operation_123 : BOOLEAN;
    signal ap_enable_operation_151 : BOOLEAN;
    signal ap_predicate_op155_store_state4 : BOOLEAN;
    signal ap_enable_operation_155 : BOOLEAN;
    signal ap_predicate_op163_store_state4 : BOOLEAN;
    signal ap_enable_operation_163 : BOOLEAN;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_condition_877 : BOOLEAN;

    component ov5640_sobel_mux_hbi IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (7 downto 0);
        din3 : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component Filter2D_k_buf_0_eOg IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        address1 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    k_buf_0_val_3_U : component Filter2D_k_buf_0_eOg
    generic map (
        DataWidth => 8,
        AddressRange => 1280,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => k_buf_0_val_3_address0,
        ce0 => k_buf_0_val_3_ce0,
        q0 => k_buf_0_val_3_q0,
        address1 => k_buf_0_val_3_address1,
        ce1 => k_buf_0_val_3_ce1,
        we1 => k_buf_0_val_3_we1,
        d1 => p_src_data_stream_V_dout);

    k_buf_0_val_4_U : component Filter2D_k_buf_0_eOg
    generic map (
        DataWidth => 8,
        AddressRange => 1280,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => k_buf_0_val_4_address0,
        ce0 => k_buf_0_val_4_ce0,
        q0 => k_buf_0_val_4_q0,
        address1 => k_buf_0_val_4_address1,
        ce1 => k_buf_0_val_4_ce1,
        we1 => k_buf_0_val_4_we1,
        d1 => k_buf_0_val_4_d1);

    k_buf_0_val_5_U : component Filter2D_k_buf_0_eOg
    generic map (
        DataWidth => 8,
        AddressRange => 1280,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => k_buf_0_val_5_address0,
        ce0 => k_buf_0_val_5_ce0,
        q0 => k_buf_0_val_5_q0,
        address1 => k_buf_0_val_5_address1,
        ce1 => k_buf_0_val_5_ce1,
        we1 => k_buf_0_val_5_we1,
        d1 => k_buf_0_val_5_d1);

    ov5640_sobel_mux_hbi_U37 : component ov5640_sobel_mux_hbi
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => right_border_buf_0_s_fu_152,
        din1 => right_border_buf_0_1_fu_156,
        din2 => ap_const_lv8_0,
        din3 => tmp_37_reg_1419,
        dout => tmp_26_fu_823_p5);

    ov5640_sobel_mux_hbi_U38 : component ov5640_sobel_mux_hbi
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => right_border_buf_0_3_fu_164,
        din1 => right_border_buf_0_4_fu_168,
        din2 => ap_const_lv8_0,
        din3 => tmp_37_reg_1419,
        dout => tmp_27_fu_841_p5);

    ov5640_sobel_mux_hbi_U39 : component ov5640_sobel_mux_hbi
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => right_border_buf_0_5_fu_172,
        din1 => right_border_buf_0_2_fu_160,
        din2 => ap_const_lv8_0,
        din3 => tmp_37_reg_1419,
        dout => tmp_28_fu_859_p5);

    ov5640_sobel_mux_hbi_U40 : component ov5640_sobel_mux_hbi
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => col_buf_0_val_0_0_fu_834_p3,
        din1 => col_buf_0_val_1_0_fu_852_p3,
        din2 => col_buf_0_val_2_0_fu_870_p3,
        din3 => tmp_23_reg_1378,
        dout => tmp_29_fu_913_p5);

    ov5640_sobel_mux_hbi_U41 : component ov5640_sobel_mux_hbi
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => col_buf_0_val_0_0_fu_834_p3,
        din1 => col_buf_0_val_1_0_fu_852_p3,
        din2 => col_buf_0_val_2_0_fu_870_p3,
        din3 => tmp_24_reg_1383,
        dout => tmp_30_fu_931_p5);

    ov5640_sobel_mux_hbi_U42 : component ov5640_sobel_mux_hbi
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => col_buf_0_val_0_0_fu_834_p3,
        din1 => col_buf_0_val_1_0_fu_852_p3,
        din2 => col_buf_0_val_2_0_fu_870_p3,
        din3 => tmp_32_reg_1388,
        dout => tmp_31_fu_949_p5);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((exitcond460_i_fu_655_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((exitcond461_i_fu_336_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                elsif (((exitcond461_i_fu_336_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    t_V_2_reg_277_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond460_i_fu_655_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                t_V_2_reg_277 <= j_V_fu_660_p2;
            elsif (((exitcond461_i_fu_336_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                t_V_2_reg_277 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    t_V_reg_266_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                t_V_reg_266 <= i_V_reg_1344;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                t_V_reg_266 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond460_i_fu_655_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                brmerge_reg_1406 <= brmerge_fu_784_p2;
                k_buf_0_val_3_addr_reg_1413 <= tmp_25_fu_789_p1(11 - 1 downto 0);
                k_buf_0_val_4_addr_reg_1426 <= tmp_25_fu_789_p1(11 - 1 downto 0);
                k_buf_0_val_5_addr_reg_1432 <= tmp_25_fu_789_p1(11 - 1 downto 0);
                or_cond_i_i_reg_1402 <= or_cond_i_i_fu_707_p2;
                or_cond_i_reg_1438 <= or_cond_i_fu_800_p2;
                tmp_37_reg_1419 <= tmp_37_fu_796_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                exitcond460_i_reg_1393 <= exitcond460_i_fu_655_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                i_V_reg_1344 <= i_V_fu_341_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond461_i_fu_336_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                icmp_reg_1358 <= icmp_fu_368_p2;
                tmp_114_1_reg_1367 <= tmp_114_1_fu_380_p2;
                tmp_12_reg_1363 <= tmp_12_fu_374_p2;
                tmp_13_reg_1371 <= tmp_13_fu_386_p2;
                tmp_23_reg_1378 <= tmp_23_fu_601_p1;
                tmp_24_reg_1383 <= tmp_24_fu_626_p1;
                tmp_32_reg_1388 <= tmp_32_fu_651_p1;
                tmp_5_reg_1349 <= tmp_5_fu_347_p2;
                tmp_70_0_not_reg_1353 <= tmp_70_0_not_fu_352_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                p_neg465_i_reg_1316 <= p_neg465_i_fu_300_p2;
                tmp_1_reg_1311 <= tmp_1_fu_294_p2;
                tmp_2_reg_1323 <= tmp_2_fu_306_p2;
                    tmp_4_reg_1328(31 downto 1) <= tmp_4_fu_318_p2(31 downto 1);
                    tmp_8_reg_1335(31 downto 1) <= tmp_8_fu_330_p2(31 downto 1);
                tmp_s_reg_1306 <= tmp_s_fu_288_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_5_reg_1349 = ap_const_lv1_1) and (icmp_reg_1358 = ap_const_lv1_1) and (or_cond_i_i_reg_1402 = ap_const_lv1_1) and (exitcond460_i_reg_1393 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                right_border_buf_0_1_fu_156 <= right_border_buf_0_s_fu_152;
                right_border_buf_0_2_fu_160 <= right_border_buf_0_5_fu_172;
                right_border_buf_0_3_fu_164 <= col_buf_0_val_1_0_fu_852_p3;
                right_border_buf_0_4_fu_168 <= right_border_buf_0_3_fu_164;
                right_border_buf_0_5_fu_172 <= col_buf_0_val_2_0_fu_870_p3;
                right_border_buf_0_s_fu_152 <= col_buf_0_val_0_0_fu_834_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond460_i_reg_1393 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                src_kernel_win_0_va_1_fu_132 <= src_kernel_win_0_va_fu_128;
                src_kernel_win_0_va_2_fu_136 <= src_kernel_win_0_va_7_fu_942_p3;
                src_kernel_win_0_va_3_fu_140 <= src_kernel_win_0_va_2_fu_136;
                src_kernel_win_0_va_4_fu_144 <= src_kernel_win_0_va_8_fu_960_p3;
                src_kernel_win_0_va_5_fu_148 <= src_kernel_win_0_va_4_fu_144;
                src_kernel_win_0_va_fu_128 <= src_kernel_win_0_va_6_fu_924_p3;
            end if;
        end if;
    end process;
    tmp_4_reg_1328(0) <= '0';
    tmp_8_reg_1335(0) <= '0';

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, exitcond461_i_fu_336_p2, ap_CS_fsm_state2, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((exitcond461_i_fu_336_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if (not(((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    ImagLoc_x_fu_682_p2 <= std_logic_vector(signed(ap_const_lv32_FFFFFFFF) + signed(t_V_2_reg_277));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state5 <= ap_CS_fsm(3);

    ap_block_pp0_assign_proc : process(ap_CS_fsm, ap_block_pp0_stage0_subdone)
    begin
                ap_block_pp0 <= ((ap_ST_fsm_pp0_stage0 = ap_CS_fsm) and (ap_const_boolean_1 = ap_block_pp0_stage0_subdone));
    end process;

        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(p_src_data_stream_V_empty_n, p_dst_data_stream_V_full_n, ap_enable_reg_pp0_iter1, ap_predicate_op154_read_state4, ap_predicate_op165_read_state4, ap_predicate_op218_write_state4)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((p_dst_data_stream_V_full_n = ap_const_logic_0) and (ap_predicate_op218_write_state4 = ap_const_boolean_1)) or ((p_src_data_stream_V_empty_n = ap_const_logic_0) and (ap_predicate_op165_read_state4 = ap_const_boolean_1)) or ((p_src_data_stream_V_empty_n = ap_const_logic_0) and (ap_predicate_op154_read_state4 = ap_const_boolean_1))));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(p_src_data_stream_V_empty_n, p_dst_data_stream_V_full_n, ap_enable_reg_pp0_iter1, ap_predicate_op154_read_state4, ap_predicate_op165_read_state4, ap_predicate_op218_write_state4)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((p_dst_data_stream_V_full_n = ap_const_logic_0) and (ap_predicate_op218_write_state4 = ap_const_boolean_1)) or ((p_src_data_stream_V_empty_n = ap_const_logic_0) and (ap_predicate_op165_read_state4 = ap_const_boolean_1)) or ((p_src_data_stream_V_empty_n = ap_const_logic_0) and (ap_predicate_op154_read_state4 = ap_const_boolean_1))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(p_src_data_stream_V_empty_n, p_dst_data_stream_V_full_n, ap_enable_reg_pp0_iter1, ap_predicate_op154_read_state4, ap_predicate_op165_read_state4, ap_predicate_op218_write_state4)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((p_dst_data_stream_V_full_n = ap_const_logic_0) and (ap_predicate_op218_write_state4 = ap_const_boolean_1)) or ((p_src_data_stream_V_empty_n = ap_const_logic_0) and (ap_predicate_op165_read_state4 = ap_const_boolean_1)) or ((p_src_data_stream_V_empty_n = ap_const_logic_0) and (ap_predicate_op154_read_state4 = ap_const_boolean_1))));
    end process;

        ap_block_state3_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state4_pp0_stage0_iter1_assign_proc : process(p_src_data_stream_V_empty_n, p_dst_data_stream_V_full_n, ap_predicate_op154_read_state4, ap_predicate_op165_read_state4, ap_predicate_op218_write_state4)
    begin
                ap_block_state4_pp0_stage0_iter1 <= (((p_dst_data_stream_V_full_n = ap_const_logic_0) and (ap_predicate_op218_write_state4 = ap_const_boolean_1)) or ((p_src_data_stream_V_empty_n = ap_const_logic_0) and (ap_predicate_op165_read_state4 = ap_const_boolean_1)) or ((p_src_data_stream_V_empty_n = ap_const_logic_0) and (ap_predicate_op154_read_state4 = ap_const_boolean_1)));
    end process;


    ap_condition_877_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, exitcond460_i_reg_1393, or_cond_i_i_reg_1402)
    begin
                ap_condition_877 <= ((or_cond_i_i_reg_1402 = ap_const_lv1_1) and (exitcond460_i_reg_1393 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, exitcond461_i_fu_336_p2, ap_CS_fsm_state2)
    begin
        if ((((exitcond461_i_fu_336_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_operation_118_assign_proc : process(exitcond460_i_fu_655_p2)
    begin
                ap_enable_operation_118 <= (exitcond460_i_fu_655_p2 = ap_const_lv1_0);
    end process;


    ap_enable_operation_121_assign_proc : process(exitcond460_i_fu_655_p2)
    begin
                ap_enable_operation_121 <= (exitcond460_i_fu_655_p2 = ap_const_lv1_0);
    end process;


    ap_enable_operation_123_assign_proc : process(exitcond460_i_fu_655_p2)
    begin
                ap_enable_operation_123 <= (exitcond460_i_fu_655_p2 = ap_const_lv1_0);
    end process;


    ap_enable_operation_145_assign_proc : process(exitcond460_i_reg_1393)
    begin
                ap_enable_operation_145 <= (exitcond460_i_reg_1393 = ap_const_lv1_0);
    end process;


    ap_enable_operation_148_assign_proc : process(exitcond460_i_reg_1393)
    begin
                ap_enable_operation_148 <= (exitcond460_i_reg_1393 = ap_const_lv1_0);
    end process;


    ap_enable_operation_151_assign_proc : process(exitcond460_i_reg_1393)
    begin
                ap_enable_operation_151 <= (exitcond460_i_reg_1393 = ap_const_lv1_0);
    end process;


    ap_enable_operation_155_assign_proc : process(ap_predicate_op155_store_state4)
    begin
                ap_enable_operation_155 <= (ap_predicate_op155_store_state4 = ap_const_boolean_1);
    end process;


    ap_enable_operation_157_assign_proc : process(ap_predicate_op157_store_state4)
    begin
                ap_enable_operation_157 <= (ap_predicate_op157_store_state4 = ap_const_boolean_1);
    end process;


    ap_enable_operation_159_assign_proc : process(ap_predicate_op159_store_state4)
    begin
                ap_enable_operation_159 <= (ap_predicate_op159_store_state4 = ap_const_boolean_1);
    end process;


    ap_enable_operation_163_assign_proc : process(ap_predicate_op163_store_state4)
    begin
                ap_enable_operation_163 <= (ap_predicate_op163_store_state4 = ap_const_boolean_1);
    end process;


    ap_enable_operation_164_assign_proc : process(ap_predicate_op164_store_state4)
    begin
                ap_enable_operation_164 <= (ap_predicate_op164_store_state4 = ap_const_boolean_1);
    end process;


    ap_enable_operation_166_assign_proc : process(ap_predicate_op166_store_state4)
    begin
                ap_enable_operation_166 <= (ap_predicate_op166_store_state4 = ap_const_boolean_1);
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_state3_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0)
    begin
                ap_enable_state3_pp0_iter0_stage0 <= ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;


    ap_enable_state4_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1)
    begin
                ap_enable_state4_pp0_iter1_stage0 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_predicate_op154_read_state4_assign_proc : process(exitcond460_i_reg_1393, or_cond_i_i_reg_1402, icmp_reg_1358)
    begin
                ap_predicate_op154_read_state4 <= ((or_cond_i_i_reg_1402 = ap_const_lv1_1) and (icmp_reg_1358 = ap_const_lv1_0) and (exitcond460_i_reg_1393 = ap_const_lv1_0));
    end process;


    ap_predicate_op155_store_state4_assign_proc : process(exitcond460_i_reg_1393, or_cond_i_i_reg_1402, icmp_reg_1358, tmp_12_reg_1363)
    begin
                ap_predicate_op155_store_state4 <= ((tmp_12_reg_1363 = ap_const_lv1_1) and (or_cond_i_i_reg_1402 = ap_const_lv1_1) and (icmp_reg_1358 = ap_const_lv1_0) and (exitcond460_i_reg_1393 = ap_const_lv1_0));
    end process;


    ap_predicate_op157_store_state4_assign_proc : process(exitcond460_i_reg_1393, or_cond_i_i_reg_1402, icmp_reg_1358, tmp_114_1_reg_1367)
    begin
                ap_predicate_op157_store_state4 <= ((tmp_114_1_reg_1367 = ap_const_lv1_1) and (or_cond_i_i_reg_1402 = ap_const_lv1_1) and (icmp_reg_1358 = ap_const_lv1_0) and (exitcond460_i_reg_1393 = ap_const_lv1_0));
    end process;


    ap_predicate_op159_store_state4_assign_proc : process(exitcond460_i_reg_1393, or_cond_i_i_reg_1402, icmp_reg_1358, tmp_12_reg_1363)
    begin
                ap_predicate_op159_store_state4 <= ((tmp_12_reg_1363 = ap_const_lv1_1) and (or_cond_i_i_reg_1402 = ap_const_lv1_1) and (icmp_reg_1358 = ap_const_lv1_0) and (exitcond460_i_reg_1393 = ap_const_lv1_0));
    end process;


    ap_predicate_op163_store_state4_assign_proc : process(exitcond460_i_reg_1393, or_cond_i_i_reg_1402, icmp_reg_1358, tmp_5_reg_1349)
    begin
                ap_predicate_op163_store_state4 <= ((tmp_5_reg_1349 = ap_const_lv1_1) and (icmp_reg_1358 = ap_const_lv1_1) and (or_cond_i_i_reg_1402 = ap_const_lv1_1) and (exitcond460_i_reg_1393 = ap_const_lv1_0));
    end process;


    ap_predicate_op164_store_state4_assign_proc : process(exitcond460_i_reg_1393, or_cond_i_i_reg_1402, icmp_reg_1358, tmp_5_reg_1349)
    begin
                ap_predicate_op164_store_state4 <= ((tmp_5_reg_1349 = ap_const_lv1_1) and (icmp_reg_1358 = ap_const_lv1_1) and (or_cond_i_i_reg_1402 = ap_const_lv1_1) and (exitcond460_i_reg_1393 = ap_const_lv1_0));
    end process;


    ap_predicate_op165_read_state4_assign_proc : process(exitcond460_i_reg_1393, or_cond_i_i_reg_1402, icmp_reg_1358, tmp_5_reg_1349)
    begin
                ap_predicate_op165_read_state4 <= ((tmp_5_reg_1349 = ap_const_lv1_1) and (icmp_reg_1358 = ap_const_lv1_1) and (or_cond_i_i_reg_1402 = ap_const_lv1_1) and (exitcond460_i_reg_1393 = ap_const_lv1_0));
    end process;


    ap_predicate_op166_store_state4_assign_proc : process(exitcond460_i_reg_1393, or_cond_i_i_reg_1402, icmp_reg_1358, tmp_5_reg_1349)
    begin
                ap_predicate_op166_store_state4 <= ((tmp_5_reg_1349 = ap_const_lv1_1) and (icmp_reg_1358 = ap_const_lv1_1) and (or_cond_i_i_reg_1402 = ap_const_lv1_1) and (exitcond460_i_reg_1393 = ap_const_lv1_0));
    end process;


    ap_predicate_op218_write_state4_assign_proc : process(exitcond460_i_reg_1393, or_cond_i_reg_1438)
    begin
                ap_predicate_op218_write_state4 <= ((or_cond_i_reg_1438 = ap_const_lv1_1) and (exitcond460_i_reg_1393 = ap_const_lv1_0));
    end process;


    ap_ready_assign_proc : process(exitcond461_i_fu_336_p2, ap_CS_fsm_state2)
    begin
        if (((exitcond461_i_fu_336_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    brmerge_fu_784_p2 <= (tmp_9_fu_702_p2 or tmp_70_0_not_reg_1353);
    col_assign_1_fu_779_p2 <= std_logic_vector(unsigned(tmp_2_reg_1323) - unsigned(x_fu_771_p3));
    col_buf_0_val_0_0_fu_834_p3 <= 
        k_buf_0_val_3_q0 when (brmerge_reg_1406(0) = '1') else 
        tmp_26_fu_823_p5;
    col_buf_0_val_1_0_fu_852_p3 <= 
        k_buf_0_val_4_q0 when (brmerge_reg_1406(0) = '1') else 
        tmp_27_fu_841_p5;
    col_buf_0_val_2_0_fu_870_p3 <= 
        k_buf_0_val_5_q0 when (brmerge_reg_1406(0) = '1') else 
        tmp_28_fu_859_p5;
    exitcond460_i_fu_655_p2 <= "1" when (t_V_2_reg_277 = tmp_s_reg_1306) else "0";
    exitcond461_i_fu_336_p2 <= "1" when (t_V_reg_266 = tmp_1_reg_1311) else "0";
    i_V_fu_341_p2 <= std_logic_vector(unsigned(t_V_reg_266) + unsigned(ap_const_lv32_1));
    icmp1_fu_676_p2 <= "0" when (tmp_33_fu_666_p4 = ap_const_lv31_0) else "1";
    icmp_fu_368_p2 <= "0" when (tmp_10_fu_358_p4 = ap_const_lv31_0) else "1";
    j_V_fu_660_p2 <= std_logic_vector(unsigned(t_V_2_reg_277) + unsigned(ap_const_lv32_1));
    k_buf_0_val_3_address0 <= tmp_25_fu_789_p1(11 - 1 downto 0);
    k_buf_0_val_3_address1 <= k_buf_0_val_3_addr_reg_1413;

    k_buf_0_val_3_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            k_buf_0_val_3_ce0 <= ap_const_logic_1;
        else 
            k_buf_0_val_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    k_buf_0_val_3_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, exitcond460_i_reg_1393, or_cond_i_i_reg_1402, icmp_reg_1358, tmp_5_reg_1349, tmp_12_reg_1363, ap_block_pp0_stage0_11001)
    begin
        if ((((tmp_5_reg_1349 = ap_const_lv1_1) and (icmp_reg_1358 = ap_const_lv1_1) and (or_cond_i_i_reg_1402 = ap_const_lv1_1) and (exitcond460_i_reg_1393 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((tmp_12_reg_1363 = ap_const_lv1_1) and (or_cond_i_i_reg_1402 = ap_const_lv1_1) and (icmp_reg_1358 = ap_const_lv1_0) and (exitcond460_i_reg_1393 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            k_buf_0_val_3_ce1 <= ap_const_logic_1;
        else 
            k_buf_0_val_3_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    k_buf_0_val_3_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, exitcond460_i_reg_1393, or_cond_i_i_reg_1402, icmp_reg_1358, tmp_5_reg_1349, tmp_12_reg_1363, ap_block_pp0_stage0_11001)
    begin
        if ((((tmp_5_reg_1349 = ap_const_lv1_1) and (icmp_reg_1358 = ap_const_lv1_1) and (or_cond_i_i_reg_1402 = ap_const_lv1_1) and (exitcond460_i_reg_1393 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((tmp_12_reg_1363 = ap_const_lv1_1) and (or_cond_i_i_reg_1402 = ap_const_lv1_1) and (icmp_reg_1358 = ap_const_lv1_0) and (exitcond460_i_reg_1393 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            k_buf_0_val_3_we1 <= ap_const_logic_1;
        else 
            k_buf_0_val_3_we1 <= ap_const_logic_0;
        end if; 
    end process;

    k_buf_0_val_4_address0 <= tmp_25_fu_789_p1(11 - 1 downto 0);
    k_buf_0_val_4_address1 <= k_buf_0_val_4_addr_reg_1426;

    k_buf_0_val_4_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            k_buf_0_val_4_ce0 <= ap_const_logic_1;
        else 
            k_buf_0_val_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    k_buf_0_val_4_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, exitcond460_i_reg_1393, or_cond_i_i_reg_1402, icmp_reg_1358, tmp_5_reg_1349, tmp_114_1_reg_1367, ap_block_pp0_stage0_11001)
    begin
        if ((((tmp_5_reg_1349 = ap_const_lv1_1) and (icmp_reg_1358 = ap_const_lv1_1) and (or_cond_i_i_reg_1402 = ap_const_lv1_1) and (exitcond460_i_reg_1393 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((tmp_114_1_reg_1367 = ap_const_lv1_1) and (or_cond_i_i_reg_1402 = ap_const_lv1_1) and (icmp_reg_1358 = ap_const_lv1_0) and (exitcond460_i_reg_1393 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            k_buf_0_val_4_ce1 <= ap_const_logic_1;
        else 
            k_buf_0_val_4_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    k_buf_0_val_4_d1_assign_proc : process(p_src_data_stream_V_dout, icmp_reg_1358, tmp_5_reg_1349, tmp_114_1_reg_1367, k_buf_0_val_3_q0, ap_condition_877)
    begin
        if ((ap_const_boolean_1 = ap_condition_877)) then
            if (((tmp_5_reg_1349 = ap_const_lv1_1) and (icmp_reg_1358 = ap_const_lv1_1))) then 
                k_buf_0_val_4_d1 <= k_buf_0_val_3_q0;
            elsif (((tmp_114_1_reg_1367 = ap_const_lv1_1) and (icmp_reg_1358 = ap_const_lv1_0))) then 
                k_buf_0_val_4_d1 <= p_src_data_stream_V_dout;
            else 
                k_buf_0_val_4_d1 <= "XXXXXXXX";
            end if;
        else 
            k_buf_0_val_4_d1 <= "XXXXXXXX";
        end if; 
    end process;


    k_buf_0_val_4_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, exitcond460_i_reg_1393, or_cond_i_i_reg_1402, icmp_reg_1358, tmp_5_reg_1349, tmp_114_1_reg_1367, ap_block_pp0_stage0_11001)
    begin
        if ((((tmp_5_reg_1349 = ap_const_lv1_1) and (icmp_reg_1358 = ap_const_lv1_1) and (or_cond_i_i_reg_1402 = ap_const_lv1_1) and (exitcond460_i_reg_1393 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((tmp_114_1_reg_1367 = ap_const_lv1_1) and (or_cond_i_i_reg_1402 = ap_const_lv1_1) and (icmp_reg_1358 = ap_const_lv1_0) and (exitcond460_i_reg_1393 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            k_buf_0_val_4_we1 <= ap_const_logic_1;
        else 
            k_buf_0_val_4_we1 <= ap_const_logic_0;
        end if; 
    end process;

    k_buf_0_val_5_address0 <= tmp_25_fu_789_p1(11 - 1 downto 0);
    k_buf_0_val_5_address1 <= k_buf_0_val_5_addr_reg_1432;

    k_buf_0_val_5_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            k_buf_0_val_5_ce0 <= ap_const_logic_1;
        else 
            k_buf_0_val_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    k_buf_0_val_5_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, exitcond460_i_reg_1393, or_cond_i_i_reg_1402, icmp_reg_1358, tmp_5_reg_1349, tmp_12_reg_1363, ap_block_pp0_stage0_11001)
    begin
        if ((((tmp_5_reg_1349 = ap_const_lv1_1) and (icmp_reg_1358 = ap_const_lv1_1) and (or_cond_i_i_reg_1402 = ap_const_lv1_1) and (exitcond460_i_reg_1393 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((tmp_12_reg_1363 = ap_const_lv1_1) and (or_cond_i_i_reg_1402 = ap_const_lv1_1) and (icmp_reg_1358 = ap_const_lv1_0) and (exitcond460_i_reg_1393 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            k_buf_0_val_5_ce1 <= ap_const_logic_1;
        else 
            k_buf_0_val_5_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    k_buf_0_val_5_d1_assign_proc : process(p_src_data_stream_V_dout, icmp_reg_1358, tmp_5_reg_1349, tmp_12_reg_1363, k_buf_0_val_4_q0, ap_condition_877)
    begin
        if ((ap_const_boolean_1 = ap_condition_877)) then
            if (((tmp_5_reg_1349 = ap_const_lv1_1) and (icmp_reg_1358 = ap_const_lv1_1))) then 
                k_buf_0_val_5_d1 <= k_buf_0_val_4_q0;
            elsif (((tmp_12_reg_1363 = ap_const_lv1_1) and (icmp_reg_1358 = ap_const_lv1_0))) then 
                k_buf_0_val_5_d1 <= p_src_data_stream_V_dout;
            else 
                k_buf_0_val_5_d1 <= "XXXXXXXX";
            end if;
        else 
            k_buf_0_val_5_d1 <= "XXXXXXXX";
        end if; 
    end process;


    k_buf_0_val_5_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, exitcond460_i_reg_1393, or_cond_i_i_reg_1402, icmp_reg_1358, tmp_5_reg_1349, tmp_12_reg_1363, ap_block_pp0_stage0_11001)
    begin
        if ((((tmp_5_reg_1349 = ap_const_lv1_1) and (icmp_reg_1358 = ap_const_lv1_1) and (or_cond_i_i_reg_1402 = ap_const_lv1_1) and (exitcond460_i_reg_1393 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((tmp_12_reg_1363 = ap_const_lv1_1) and (or_cond_i_i_reg_1402 = ap_const_lv1_1) and (icmp_reg_1358 = ap_const_lv1_0) and (exitcond460_i_reg_1393 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            k_buf_0_val_5_we1 <= ap_const_logic_1;
        else 
            k_buf_0_val_5_we1 <= ap_const_logic_0;
        end if; 
    end process;

    not_i_i_fu_1140_p2 <= "0" when (tmp_36_fu_1124_p4 = ap_const_lv3_0) else "1";
    or_cond_i496_i_1_fu_479_p2 <= (tmp_140_1_fu_474_p2 and rev1_fu_468_p2);
    or_cond_i496_i_2_fu_542_p2 <= (tmp_140_2_fu_537_p2 and rev2_fu_531_p2);
    or_cond_i496_i_fu_416_p2 <= (tmp_16_fu_411_p2 and rev_fu_405_p2);
    or_cond_i_fu_800_p2 <= (icmp_reg_1358 and icmp1_fu_676_p2);
    or_cond_i_i_fu_707_p2 <= (tmp_9_fu_702_p2 and rev3_fu_696_p2);
    overflow_fu_1146_p2 <= (tmp_i_i_fu_1134_p2 and not_i_i_fu_1140_p2);
    p_Result_s_fu_1092_p3 <= p_Val2_s_fu_1086_p2(10 downto 10);
    p_Val2_1_fu_1118_p2 <= std_logic_vector(unsigned(tmp24_fu_1100_p2) + unsigned(tmp25_fu_1112_p2));
    p_Val2_s_fu_1086_p2 <= std_logic_vector(unsigned(tmp21_fu_1064_p2) + unsigned(tmp22_fu_1080_p2));
    p_assign_1_fu_721_p2 <= std_logic_vector(unsigned(ap_const_lv32_1) - unsigned(t_V_2_reg_277));
    p_assign_2_fu_740_p2 <= std_logic_vector(unsigned(tmp_8_reg_1335) - unsigned(p_p2_i_i_fu_727_p3));
    p_assign_3_fu_745_p3 <= 
        ImagLoc_x_fu_682_p2 when (or_cond_i_i_fu_707_p2(0) = '1') else 
        p_assign_2_fu_740_p2;
    p_assign_6_1_fu_454_p2 <= std_logic_vector(signed(ap_const_lv32_FFFFFFFE) + signed(t_V_reg_266));
    p_assign_6_2_fu_517_p2 <= std_logic_vector(signed(ap_const_lv32_FFFFFFFD) + signed(t_V_reg_266));
    p_assign_7_1_fu_493_p2 <= std_logic_vector(unsigned(ap_const_lv32_2) - unsigned(t_V_reg_266));
    p_assign_7_2_fu_556_p2 <= std_logic_vector(unsigned(ap_const_lv32_3) - unsigned(t_V_reg_266));
    p_assign_7_fu_430_p2 <= std_logic_vector(unsigned(ap_const_lv32_1) - unsigned(t_V_reg_266));
    p_assign_8_1_fu_512_p2 <= std_logic_vector(unsigned(tmp_4_reg_1328) - unsigned(p_p2_i497_i_1_fu_499_p3));
    p_assign_8_2_fu_575_p2 <= std_logic_vector(unsigned(tmp_4_reg_1328) - unsigned(p_p2_i497_i_2_fu_562_p3));
    p_assign_8_fu_449_p2 <= std_logic_vector(unsigned(tmp_4_reg_1328) - unsigned(p_p2_i497_i_fu_436_p3));

    p_dst_data_stream_V_blk_n_assign_proc : process(p_dst_data_stream_V_full_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, exitcond460_i_reg_1393, or_cond_i_reg_1438)
    begin
        if (((or_cond_i_reg_1438 = ap_const_lv1_1) and (exitcond460_i_reg_1393 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_dst_data_stream_V_blk_n <= p_dst_data_stream_V_full_n;
        else 
            p_dst_data_stream_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    p_dst_data_stream_V_din <= 
        p_mux_i_i_cast_fu_1152_p3 when (tmp_1_i_i_fu_1160_p2(0) = '1') else 
        p_Val2_1_fu_1118_p2;

    p_dst_data_stream_V_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op218_write_state4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op218_write_state4 = ap_const_boolean_1))) then 
            p_dst_data_stream_V_write <= ap_const_logic_1;
        else 
            p_dst_data_stream_V_write <= ap_const_logic_0;
        end if; 
    end process;

    p_mux_i_i_cast_fu_1152_p3 <= 
        ap_const_lv8_FF when (tmp_i_i_fu_1134_p2(0) = '1') else 
        ap_const_lv8_0;
    p_neg465_i_fu_300_p2 <= std_logic_vector(signed(ap_const_lv32_FFFFFFFF) + signed(p_src_rows_V_read));
    p_p2_i497_i_1_fu_499_p3 <= 
        p_assign_7_1_fu_493_p2 when (tmp_20_fu_485_p3(0) = '1') else 
        p_assign_6_1_fu_454_p2;
    p_p2_i497_i_1_p_assig_fu_605_p3 <= 
        p_p2_i497_i_1_fu_499_p3 when (tmp_149_1_fu_507_p2(0) = '1') else 
        p_assign_8_1_fu_512_p2;
    p_p2_i497_i_2_fu_562_p3 <= 
        p_assign_7_2_fu_556_p2 when (tmp_22_fu_548_p3(0) = '1') else 
        p_assign_6_2_fu_517_p2;
    p_p2_i497_i_2_p_assig_fu_630_p3 <= 
        p_p2_i497_i_2_fu_562_p3 when (tmp_149_2_fu_570_p2(0) = '1') else 
        p_assign_8_2_fu_575_p2;
    p_p2_i497_i_fu_436_p3 <= 
        p_assign_7_fu_430_p2 when (tmp_17_fu_422_p3(0) = '1') else 
        tmp_14_fu_391_p2;
    p_p2_i497_i_p_assign_8_fu_580_p3 <= 
        p_p2_i497_i_fu_436_p3 when (tmp_18_fu_444_p2(0) = '1') else 
        p_assign_8_fu_449_p2;
    p_p2_i_i_fu_727_p3 <= 
        p_assign_1_fu_721_p2 when (tmp_35_fu_713_p3(0) = '1') else 
        ImagLoc_x_fu_682_p2;
    p_shl_cast_fu_1002_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl_fu_994_p3),10));
    p_shl_fu_994_p3 <= (src_kernel_win_0_va_3_fu_140 & ap_const_lv1_0);

    p_src_data_stream_V_blk_n_assign_proc : process(p_src_data_stream_V_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, exitcond460_i_reg_1393, or_cond_i_i_reg_1402, icmp_reg_1358, tmp_5_reg_1349)
    begin
        if ((((tmp_5_reg_1349 = ap_const_lv1_1) and (icmp_reg_1358 = ap_const_lv1_1) and (or_cond_i_i_reg_1402 = ap_const_lv1_1) and (exitcond460_i_reg_1393 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((or_cond_i_i_reg_1402 = ap_const_lv1_1) and (icmp_reg_1358 = ap_const_lv1_0) and (exitcond460_i_reg_1393 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            p_src_data_stream_V_blk_n <= p_src_data_stream_V_empty_n;
        else 
            p_src_data_stream_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    p_src_data_stream_V_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op154_read_state4, ap_predicate_op165_read_state4, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op165_read_state4 = ap_const_boolean_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op154_read_state4 = ap_const_boolean_1)))) then 
            p_src_data_stream_V_read <= ap_const_logic_1;
        else 
            p_src_data_stream_V_read <= ap_const_logic_0;
        end if; 
    end process;

    r_V_0_cast_fu_976_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(src_kernel_win_0_va_5_fu_148),9));
    r_V_10_1_2_fu_1024_p3 <= (src_kernel_win_0_va_7_fu_942_p3 & ap_const_lv1_0);
    r_V_10_1_fu_1006_p2 <= std_logic_vector(unsigned(ap_const_lv10_0) - unsigned(p_shl_cast_fu_1002_p1));
    r_V_10_2_fu_1046_p2 <= std_logic_vector(unsigned(ap_const_lv9_0) - unsigned(r_V_2_cast_fu_1042_p1));
    r_V_2_cast_fu_1042_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(src_kernel_win_0_va_1_fu_132),9));
    rev1_fu_468_p2 <= (tmp_19_fu_460_p3 xor ap_const_lv1_1);
    rev2_fu_531_p2 <= (tmp_21_fu_523_p3 xor ap_const_lv1_1);
    rev3_fu_696_p2 <= (tmp_34_fu_688_p3 xor ap_const_lv1_1);
    rev_fu_405_p2 <= (tmp_15_fu_397_p3 xor ap_const_lv1_1);
    row_assign_9_1_fu_621_p2 <= std_logic_vector(unsigned(p_neg465_i_reg_1316) - unsigned(y_1_fu_613_p3));
    row_assign_9_2_fu_646_p2 <= std_logic_vector(unsigned(p_neg465_i_reg_1316) - unsigned(y_2_fu_638_p3));
    row_assign_9_fu_596_p2 <= std_logic_vector(unsigned(p_neg465_i_reg_1316) - unsigned(y_fu_588_p3));
    sel_tmp7_fu_759_p2 <= (tmp_9_not_fu_753_p2 or tmp_34_fu_688_p3);
    sel_tmp8_fu_765_p2 <= (tmp_11_fu_735_p2 and sel_tmp7_fu_759_p2);
    src_kernel_win_0_va_6_fu_924_p3 <= 
        tmp_29_fu_913_p5 when (tmp_13_reg_1371(0) = '1') else 
        col_buf_0_val_0_0_fu_834_p3;
    src_kernel_win_0_va_7_fu_942_p3 <= 
        tmp_30_fu_931_p5 when (tmp_13_reg_1371(0) = '1') else 
        col_buf_0_val_1_0_fu_852_p3;
    src_kernel_win_0_va_8_fu_960_p3 <= 
        tmp_31_fu_949_p5 when (tmp_13_reg_1371(0) = '1') else 
        col_buf_0_val_2_0_fu_870_p3;
        sum_V_0_2_cast_cast_fu_990_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sum_V_0_2_fu_984_p2),10));

    sum_V_0_2_fu_984_p2 <= std_logic_vector(unsigned(tmp_156_0_2_cast_fu_980_p1) - unsigned(r_V_0_cast_fu_976_p1));
    tmp21_fu_1064_p2 <= std_logic_vector(signed(tmp_156_2_cast_fu_1052_p1) + signed(tmp_156_1_cast_fu_1012_p1));
    tmp22_fu_1080_p2 <= std_logic_vector(unsigned(tmp_156_1_cast_63_fu_1032_p1) + unsigned(tmp23_cast_fu_1076_p1));
        tmp23_cast_fu_1076_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp23_fu_1070_p2),11));

    tmp23_fu_1070_p2 <= std_logic_vector(unsigned(tmp_156_2_2_cast_cas_fu_1060_p1) + unsigned(sum_V_0_2_cast_cast_fu_990_p1));
    tmp24_fu_1100_p2 <= std_logic_vector(unsigned(tmp_41_fu_1020_p1) + unsigned(tmp_40_fu_1016_p1));
    tmp25_fu_1112_p2 <= std_logic_vector(unsigned(tmp_42_fu_1036_p2) + unsigned(tmp26_fu_1106_p2));
    tmp26_fu_1106_p2 <= std_logic_vector(unsigned(src_kernel_win_0_va_6_fu_924_p3) + unsigned(tmp_43_fu_1056_p1));
    tmp_10_fu_358_p4 <= t_V_reg_266(31 downto 1);
    tmp_114_1_fu_380_p2 <= "1" when (t_V_reg_266 = ap_const_lv32_0) else "0";
    tmp_11_fu_735_p2 <= "1" when (signed(p_p2_i_i_fu_727_p3) < signed(p_src_cols_V_read)) else "0";
    tmp_12_fu_374_p2 <= "1" when (t_V_reg_266 = ap_const_lv32_1) else "0";
    tmp_13_fu_386_p2 <= "1" when (unsigned(t_V_reg_266) > unsigned(p_src_rows_V_read)) else "0";
    tmp_140_1_fu_474_p2 <= "1" when (signed(p_assign_6_1_fu_454_p2) < signed(p_src_rows_V_read)) else "0";
    tmp_140_2_fu_537_p2 <= "1" when (signed(p_assign_6_2_fu_517_p2) < signed(p_src_rows_V_read)) else "0";
    tmp_149_1_fu_507_p2 <= "1" when (signed(p_p2_i497_i_1_fu_499_p3) < signed(p_src_rows_V_read)) else "0";
    tmp_149_2_fu_570_p2 <= "1" when (signed(p_p2_i497_i_2_fu_562_p3) < signed(p_src_rows_V_read)) else "0";
    tmp_14_fu_391_p2 <= std_logic_vector(signed(ap_const_lv32_FFFFFFFF) + signed(t_V_reg_266));
    tmp_156_0_2_cast_fu_980_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(src_kernel_win_0_va_8_fu_960_p3),9));
    tmp_156_1_cast_63_fu_1032_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(r_V_10_1_2_fu_1024_p3),11));
        tmp_156_1_cast_fu_1012_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_10_1_fu_1006_p2),11));

    tmp_156_2_2_cast_cas_fu_1060_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(src_kernel_win_0_va_6_fu_924_p3),10));
        tmp_156_2_cast_fu_1052_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_10_2_fu_1046_p2),11));

    tmp_15_fu_397_p3 <= tmp_14_fu_391_p2(31 downto 31);
    tmp_16_fu_411_p2 <= "1" when (signed(tmp_14_fu_391_p2) < signed(p_src_rows_V_read)) else "0";
    tmp_17_fu_422_p3 <= tmp_14_fu_391_p2(31 downto 31);
    tmp_18_fu_444_p2 <= "1" when (signed(p_p2_i497_i_fu_436_p3) < signed(p_src_rows_V_read)) else "0";
    tmp_19_fu_460_p3 <= p_assign_6_1_fu_454_p2(31 downto 31);
    tmp_1_fu_294_p2 <= std_logic_vector(unsigned(ap_const_lv32_2) + unsigned(p_src_rows_V_read));
    tmp_1_i_i_fu_1160_p2 <= (p_Result_s_fu_1092_p3 or overflow_fu_1146_p2);
    tmp_20_fu_485_p3 <= p_assign_6_1_fu_454_p2(31 downto 31);
    tmp_21_fu_523_p3 <= p_assign_6_2_fu_517_p2(31 downto 31);
    tmp_22_fu_548_p3 <= p_assign_6_2_fu_517_p2(31 downto 31);
    tmp_23_fu_601_p1 <= row_assign_9_fu_596_p2(2 - 1 downto 0);
    tmp_24_fu_626_p1 <= row_assign_9_1_fu_621_p2(2 - 1 downto 0);
    tmp_25_fu_789_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(x_fu_771_p3),64));
    tmp_2_fu_306_p2 <= std_logic_vector(unsigned(ap_const_lv32_3) + unsigned(p_src_cols_V_read));
    tmp_32_fu_651_p1 <= row_assign_9_2_fu_646_p2(2 - 1 downto 0);
    tmp_33_fu_666_p4 <= t_V_2_reg_277(31 downto 1);
    tmp_34_fu_688_p3 <= ImagLoc_x_fu_682_p2(31 downto 31);
    tmp_35_fu_713_p3 <= ImagLoc_x_fu_682_p2(31 downto 31);
    tmp_36_fu_1124_p4 <= p_Val2_s_fu_1086_p2(10 downto 8);
    tmp_37_fu_796_p1 <= col_assign_1_fu_779_p2(2 - 1 downto 0);
    tmp_3_fu_312_p2 <= std_logic_vector(shift_left(unsigned(p_src_rows_V_read),to_integer(unsigned('0' & ap_const_lv32_1(31-1 downto 0)))));
    tmp_40_fu_1016_p1 <= sum_V_0_2_fu_984_p2(8 - 1 downto 0);
    tmp_41_fu_1020_p1 <= r_V_10_1_fu_1006_p2(8 - 1 downto 0);
    tmp_42_fu_1036_p2 <= std_logic_vector(shift_left(unsigned(src_kernel_win_0_va_7_fu_942_p3),to_integer(unsigned('0' & ap_const_lv8_1(8-1 downto 0)))));
    tmp_43_fu_1056_p1 <= r_V_10_2_fu_1046_p2(8 - 1 downto 0);
    tmp_4_fu_318_p2 <= std_logic_vector(unsigned(ap_const_lv32_2) + unsigned(tmp_3_fu_312_p2));
    tmp_5_fu_347_p2 <= "1" when (unsigned(t_V_reg_266) < unsigned(p_src_rows_V_read)) else "0";
    tmp_70_0_not_fu_352_p2 <= (tmp_5_fu_347_p2 xor ap_const_lv1_1);
    tmp_7_fu_324_p2 <= std_logic_vector(shift_left(unsigned(p_src_cols_V_read),to_integer(unsigned('0' & ap_const_lv32_1(31-1 downto 0)))));
    tmp_8_fu_330_p2 <= std_logic_vector(signed(ap_const_lv32_FFFFFFFE) + signed(tmp_7_fu_324_p2));
    tmp_9_fu_702_p2 <= "1" when (signed(ImagLoc_x_fu_682_p2) < signed(p_src_cols_V_read)) else "0";
    tmp_9_not_fu_753_p2 <= (tmp_9_fu_702_p2 xor ap_const_lv1_1);
    tmp_i_i_fu_1134_p2 <= (p_Result_s_fu_1092_p3 xor ap_const_lv1_1);
    tmp_s_fu_288_p2 <= std_logic_vector(unsigned(ap_const_lv32_2) + unsigned(p_src_cols_V_read));
    x_fu_771_p3 <= 
        p_p2_i_i_fu_727_p3 when (sel_tmp8_fu_765_p2(0) = '1') else 
        p_assign_3_fu_745_p3;
    y_1_fu_613_p3 <= 
        p_assign_6_1_fu_454_p2 when (or_cond_i496_i_1_fu_479_p2(0) = '1') else 
        p_p2_i497_i_1_p_assig_fu_605_p3;
    y_2_fu_638_p3 <= 
        p_assign_6_2_fu_517_p2 when (or_cond_i496_i_2_fu_542_p2(0) = '1') else 
        p_p2_i497_i_2_p_assig_fu_630_p3;
    y_fu_588_p3 <= 
        tmp_14_fu_391_p2 when (or_cond_i496_i_fu_416_p2(0) = '1') else 
        p_p2_i497_i_p_assign_8_fu_580_p3;
end behav;
